--- #YAML:1.0
name: Erob-L4Env
version: 0.01_11
author: ~
abstract: Perl extension to the L4Env API
license: perl
provides:
  Erob::L4Env:
    file: lib/Erob/L4Env.pm
    version: 0.01_11
generated_by: Module::Build version 0.2606
